### ISSUE TITLE
macro inherited bug

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#911]
```ruby
class A
  macro inherited
    $singleton{{@type.name.id}} = 1
  end

  macro inc
    $singleton{{@type.name.id}} += 1
  end
end

class B < A
  inc
end
```

this works in crystal 0.5.5
```
  1.     $singletonB += 1
  2.   

    $singletonB += 1
                ^

undefined method '+' for Nil

```

**Comment by asterite** [comment]
This is because the `inherited` macro is executed after the whole class definition is evaluated. In Ruby it's executed right after the first line `class B < A`.

At some point I changed the semantic so I could do [this](http://play.crystal-lang.org/#/r/63y), because in Ruby if you do the [same](http://carc.in/#/r/63z) you will see that Child doesn't get a name set, and it's because the "new" method is invoked before the initialize is defined.

One solution is to have two hooks, `before_inherited` and `after_inherited`, but that makes things more complex. Another solution is to first define all methods of a class (without typing things like assignments) and then run the hooks. But this is a bit harder, because we'll also need to expand some macros that define methods, but it's doable.

In any case, the behaviour of `inherited` should match that of Ruby: be executed as soon as the type in inherited.

**Comment by kostya** [comment]
in problem to compile this:
https://github.com/kostya/http_parser.cr/blob/master/src/common_parser.cr#L98

**Comment by jhass** [comment]
@kostya why don't you use a pattern like this? https://github.com/jhass/DeBot/blob/master/framework/src/framework/bot.cr#L17 (that can work on a class level too), or something like

```cr
module Foo
  CALLBACKS = {} of CommonParser.class => String -> Bool

  macro callback
    CALLBACKS[{{@type.id}}] = ->(path : String) { path == "globals are ugly" }
  end
end
```

(just showing the idea, don't remember the specifics).

**Comment by kostya** [comment]
another example inherited and class method
```ruby
class A
  VALUES = {} of String => Array(Int32)

  macro inherited
    VALUES[{{@type.name.stringify}}] = [] of Int32
    def self.value
      VALUES[{{@type.name.stringify}}].not_nil!
    end
  end

  macro set(x)
    self.class.value << {{x}}
  end

  macro set2(x)
    VALUES[{{@type.name.stringify}}].not_nil! << {{x}}
  end
end

class B < A
  set(10)
end
```

```
  1.     self.class.value << 10
  2.   

    self.class.value << 10
               ^~~~~

undefined method 'value' for Class

```

but set2 works

**Comment by jhass** [comment]
well the macro is evaluated in the class scope there but you're assuming instance scope, `self.value` should work.
