### ISSUE TITLE
can't compile on linux 0.7.0

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#597]
```
crystal eval 'p 1'
/home/kostya/crystal-0.7.0-1/bin/../embedded/lib/../lib/libevent.a(event.o): In function `detect_monotonic':
event.c:(.text+0xca2): undefined reference to `clock_gettime'
/home/kostya/crystal-0.7.0-1/bin/../embedded/lib/../lib/libevent.a(event.o): In function `gettime':
event.c:(.text+0xd86): undefined reference to `clock_gettime'
collect2: выполнение ld завершилось с кодом возврата 1
```

may be because of gcc

**Comment by kostya** [comment]
it compiles with `-lrt -levent` if i change it to `-levent -lrt` seems fixed.

**Comment by asterite** [comment]
Oh... :-(

Can you confirm that changing the order of the `@[Link]` declarations [here](https://github.com/manastech/crystal/blob/master/src/event/lib_event2.cr#L1-L2) fixes the problem? If so, I'll shortly release 0.7.1.

**Comment by jhass** [comment]
I can't confirm the issue over here.

**Comment by asterite** [comment]
Yes, on my trusty64 VM it doesn't happen neither...

**Comment by kostya** [comment]
can't confirm because can't recompile compiler, but changing the order in console fixed it.
`export cc=clang` also fixed it.

```
cc -o 1 main.o -L /home/kostya/crystal-0.7.0-1/embedded/lib/  -lrt -levent -lpcl -lpcre -lgc -lpthread -lunwind 
/home/kostya/crystal-0.7.0-1/embedded/lib//libevent.a(event.o): In function `detect_monotonic':
event.c:(.text+0xca2): undefined reference to `clock_gettime'
/home/kostya/crystal-0.7.0-1/embedded/lib//libevent.a(event.o): In function `gettime':
event.c:(.text+0xd86): undefined reference to `clock_gettime'
collect2: выполнение ld завершилось с кодом возврата 1
```

```
cc -o 1 main.o -L /home/kostya/crystal-0.7.0-1/embedded/lib/ -levent -lrt -lpcl -lpcre -lgc -lpthread -lunwind
ok
```

```
clang -o 1 /main.o -L /home/kostya/crystal-0.7.0-1/embedded/lib/  -lrt -levent -lpcl -lpcre -lgc -lpthread -lunwind
ok
```

**Comment by asterite** [comment]
So which order is the one that works? `rt event` or `event rt`?

**Comment by kostya** [comment]
`-levent -lrt` works

**Comment by asterite** [comment]
I just released 0.7.1 because I think `gcc` might be the default for many linuxes so it's better that this always works. @kostya let me know if it works well now. Thanks for reporting, as always :-)
